engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR2"
  phpmd:
      enabled: true
ratings:
   paths:
   - "core/**/*"
   - "components/**/*"
   - "**.php"
exclude_paths:
- "libs/**/*"
- "test/**/*"
- "vendor/**/*"
- "db/**/*"